<?php

return [
    [
        'id' => 'snake',
        'title' => 'Snake',
        'category' => 'quick',
        'subcategory' => 'arcade',
        'description' => 'Guide the line, collect supplies, and avoid running into yourself.',
        'path' => '/games/snake/',
        'module' => '/games/snake/module.js',
        'styles' => [],
        'assets' => ['/games/snake/assets/splash.png', '/games/snake/assets/home.png'],
        'enabled' => true,
        'order' => 10,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['offline', 'quick', 'mobile-friendly'],
        'estimated_minutes' => 3,
        'learning_value' => null,
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'landscape',
        'launch' => [
            'start_label' => 'Start Game',
            'objective' => 'Collect supplies, grow longer, and avoid walls or your own trail.',
            'controls' => ['Arrow keys', 'Virtual joystick', 'Pause / Restart'],
            'splash_image' => '/games/snake/assets/splash.png',
            'home_image' => '/games/snake/assets/home.png',
        ],
        'icon' => 'S',
        'icon_image' => '/games/snake/assets/icon.png',
    ],
    [
        'id' => 'memory',
        'title' => 'Memory Cards',
        'category' => 'quick',
        'subcategory' => 'cards',
        'description' => 'Match preparedness symbols in a compact memory game.',
        'path' => '/games/memory/',
        'module' => '/games/memory/module.js',
        'styles' => [],
        'assets' => ['/games/memory/assets/splash.png', '/games/memory/assets/home.png'],
        'enabled' => true,
        'order' => 20,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['offline', 'quick', 'memory'],
        'estimated_minutes' => 4,
        'learning_value' => null,
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'any',
        'launch' => [
            'start_label' => 'Start Matching',
            'objective' => 'Open cards and match every preparedness symbol pair.',
            'controls' => ['Tap or click cards'],
            'splash_image' => '/games/memory/assets/splash.png',
            'home_image' => '/games/memory/assets/home.png',
        ],
        'icon' => 'M',
        'icon_image' => '/games/memory/assets/icon.png',
    ],
    [
        'id' => 'breakout',
        'title' => 'Breakout',
        'category' => 'quick',
        'subcategory' => 'arcade',
        'description' => 'Clear the blocks with a paddle and ball.',
        'path' => '/games/breakout/',
        'module' => '/games/breakout/module.js',
        'styles' => [],
        'assets' => ['/games/breakout/assets/splash.png', '/games/breakout/assets/home.png'],
        'enabled' => true,
        'order' => 30,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['offline', 'quick', 'arcade'],
        'estimated_minutes' => 3,
        'learning_value' => null,
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'landscape',
        'launch' => [
            'start_label' => 'Start Breakout',
            'objective' => 'Keep the ball in play and clear every block.',
            'controls' => ['Arrow keys', 'Touch or drag paddle'],
            'splash_image' => '/games/breakout/assets/splash.png',
            'home_image' => '/games/breakout/assets/home.png',
        ],
        'icon' => 'B',
        'icon_image' => '/games/breakout/assets/icon.png',
    ],
    [
        'id' => 'tetris',
        'title' => 'Tetris',
        'category' => 'quick',
        'subcategory' => 'puzzle',
        'description' => 'Stack falling blocks, clear complete lines, and keep the board open.',
        'path' => '/games/tetris/',
        'module' => '/games/tetris/module.js',
        'styles' => [],
        'assets' => ['/games/tetris/assets/splash.png', '/games/tetris/assets/home.png'],
        'enabled' => true,
        'order' => 40,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['offline', 'quick', 'puzzle', 'mobile-friendly'],
        'estimated_minutes' => 5,
        'learning_value' => null,
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'portrait',
        'launch' => [
            'start_label' => 'Start Tetris',
            'objective' => 'Move, rotate, and drop falling blocks to clear complete lines.',
            'controls' => ['Touch D-pad', 'Rotate / Drop buttons', 'Keyboard arrows'],
            'splash_image' => '/games/tetris/assets/splash.png',
            'home_image' => '/games/tetris/assets/home.png',
        ],
        'icon' => 'T',
        'icon_image' => '/games/tetris/assets/icon.png',
    ],
    [
        'id' => 'pacman',
        'title' => 'Supply Run',
        'category' => 'quick',
        'subcategory' => 'arcade',
        'description' => 'Navigate the route, collect supplies, and avoid patrol hazards.',
        'path' => '/games/pacman/',
        'module' => '/games/pacman/module.js',
        'styles' => [],
        'assets' => ['/games/pacman/assets/splash.png', '/games/pacman/assets/home.png'],
        'enabled' => true,
        'order' => 50,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['offline', 'quick', 'mobile-friendly', 'maze'],
        'estimated_minutes' => 4,
        'learning_value' => null,
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'portrait',
        'launch' => [
            'start_label' => 'Start Supply Run',
            'objective' => 'Collect every supply marker, use power kits, and avoid patrol hazards.',
            'controls' => ['Touch D-pad', 'Keyboard arrows', 'Pause / Restart'],
            'splash_image' => '/games/pacman/assets/splash.png',
            'home_image' => '/games/pacman/assets/home.png',
        ],
        'icon' => 'P',
        'icon_image' => '/games/pacman/assets/icon.png',
    ],
    [
        'id' => 'emergency-kit-quiz',
        'title' => 'Emergency Kit Quiz',
        'category' => 'learning',
        'subcategory' => 'preparedness',
        'description' => 'Practice identifying useful items for a basic emergency kit.',
        'path' => '/games/emergency-kit-quiz/',
        'enabled' => true,
        'order' => 110,
        'mode_visibility' => ['normal', 'monitoring', 'active_incident'],
        'tags' => ['offline', 'preparedness', 'quiz'],
        'estimated_minutes' => 5,
        'learning_value' => 'Emergency preparedness',
        'content_rating' => 'general',
        'emergency_priority' => 'medium',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'any',
        'icon' => 'K',
    ],
    [
        'id' => 'first-aid-matching',
        'title' => 'First Aid Matching',
        'category' => 'learning',
        'subcategory' => 'public-safety',
        'description' => 'Match simple first-aid actions with their common situations.',
        'path' => '/games/first-aid-matching/',
        'enabled' => true,
        'order' => 120,
        'mode_visibility' => ['normal', 'monitoring', 'active_incident'],
        'tags' => ['offline', 'first-aid', 'matching'],
        'estimated_minutes' => 5,
        'learning_value' => 'Basic first aid awareness',
        'content_rating' => 'general',
        'emergency_priority' => 'medium',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'any',
        'icon' => 'F',
    ],
    [
        'id' => 'hazard-awareness',
        'title' => 'Hazard Awareness Quiz',
        'category' => 'learning',
        'subcategory' => 'barangay-safety',
        'description' => 'Review common local hazards and practical safety choices.',
        'path' => '/games/hazard-awareness/',
        'enabled' => true,
        'order' => 130,
        'mode_visibility' => ['normal', 'monitoring', 'active_incident'],
        'tags' => ['offline', 'hazards', 'barangay', 'quiz'],
        'estimated_minutes' => 5,
        'learning_value' => 'Local hazard awareness',
        'content_rating' => 'general',
        'emergency_priority' => 'medium',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'any',
        'icon' => 'H',
    ],
    [
        'id' => 'retro-corner',
        'title' => 'Retro Corner',
        'category' => 'retro',
        'subcategory' => 'placeholder',
        'description' => 'Reserved for future homebrew, public-domain, open-source, or properly licensed retro games.',
        'path' => '/retro/',
        'enabled' => true,
        'order' => 210,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['offline', 'retro', 'licensed-content-only'],
        'estimated_minutes' => null,
        'learning_value' => null,
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'landscape',
        'icon' => 'R',
    ],
    [
        'id' => 'barangay-trivia',
        'title' => 'Barangay Trivia',
        'category' => 'local',
        'subcategory' => 'placeholder',
        'description' => 'Placeholder for future barangay-specific games and quizzes.',
        'path' => '#',
        'enabled' => false,
        'order' => 310,
        'mode_visibility' => ['normal', 'monitoring'],
        'tags' => ['local', 'barangay'],
        'estimated_minutes' => null,
        'learning_value' => 'Local civic awareness',
        'content_rating' => 'general',
        'emergency_priority' => 'low',
        'requires_keyboard' => false,
        'supports_touch' => true,
        'orientation' => 'any',
        'icon' => 'L',
    ],
];
